// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8eKLo4G6qFetlvtCLRUJ-tYzVkk7KhNA',
    appId: '1:982358825220:web:4bd898db20385632699851',
    messagingSenderId: '982358825220',
    projectId: 'fir-dersleri-207db',
    authDomain: 'fir-dersleri-207db.firebaseapp.com',
    storageBucket: 'fir-dersleri-207db.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADKmlhdbjF20lKLQkpofsel3CUVfRrLIM',
    appId: '1:982358825220:android:a1465bac55cf9d37699851',
    messagingSenderId: '982358825220',
    projectId: 'fir-dersleri-207db',
    storageBucket: 'fir-dersleri-207db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXKw3rWJyfT1V0AfZM6dmJ0BJGJhZCmAw',
    appId: '1:982358825220:ios:f1bd940269c0bb40699851',
    messagingSenderId: '982358825220',
    projectId: 'fir-dersleri-207db',
    storageBucket: 'fir-dersleri-207db.firebasestorage.app',
    iosBundleId: 'com.yasinaktas.firebasemyproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXKw3rWJyfT1V0AfZM6dmJ0BJGJhZCmAw',
    appId: '1:982358825220:ios:ee6a5d945d939c4a699851',
    messagingSenderId: '982358825220',
    projectId: 'fir-dersleri-207db',
    storageBucket: 'fir-dersleri-207db.firebasestorage.app',
    iosBundleId: 'com.example.firebasemyproject',
  );
}
